steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/test-infrastructure-288509/helloword-demo:$TAG_NAME', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/test-infrastructure-288509/helloword-demo:$TAG_NAME']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gs://test_ci_cd_k8s/deployment.yaml
  - --image=us.gcr.io/test-infrastructure-288509/helloword-demo:$TAG_NAME
  - --location=us-central1-c
  - --cluster=cluster-1
