apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloword
  name: helloword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloword
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloword
    spec:
      containers:
      - image: gcr.io/test-infrastructure/helloword-demo:1.0
        name: helloword-demo
        resources: {}
status: {}

